"""Reviewed public source records, never athlete data or generated recommendations.

Records expire and are rechecked before use. Import does not fetch or call AI.
"""

CHECKED = "2026-09-23T16:17:39Z"
EXPIRES = "2026-09-30T16:17:39Z"
# Review again before the imminent deposit-balance date, not after a seven-day TTL.
ORLANDO_EXPIRES = "2026-09-25T00:00:00Z"
# The linked GMTM page did not expose current details. Keep its previous receipt;
# a fresh schedule read does not renew that source or reopen this ended combine.
COMBINE_ENTRY_CHECKED = "2026-09-10T16:30:06Z"
COMBINE_ENTRY_EXPIRES = "2026-09-17T16:30:06Z"
DIGITAL = "https://www.usafootball.com/national-team/digital-combine"
CONTACT = "https://usafootball.com/national-team"
GMTM_COMBINE = "https://gmtm.com/virtuals/1318/2027-u-s-flag-national-team-adult-digital-combine-2"

# Field-by-field evidence and excluded stale/test sources:
# docs/research/adult-flag-events-2026-09-23.md. Review expiry is SPARQ's
# internal freshness policy; it is never presented as an organizer's deadline.
RECORDS = (
    {
        "id": "usaf-adult-digital-combine-2-2027", "title": "Adult Flag Digital Combine 2",
        "organization": "USA Football", "kind": "assessment", "format": "remote",
        "categories": ["men", "women"], "status": "check_details",
        "focuses": ["national_team"], "state": None, "participation": "individual",
        "summary": "The published window ended September 21, 2026. This record is retained for history and excluded from current opportunities; a later combine is still to be announced.",
        "valid_until": COMBINE_ENTRY_EXPIRES, "opens_at": None,
        # Conservative internal withdrawal, not a claim about the missing timezone.
        "closes_at": "2026-09-21T00:00:00Z",
        "facts": [
            {"key": "dates", "label": "Published window", "value": "Aug 10–Sep 21, 2026. The linked adult combine names the 2027 cycle. Cutoff time and timezone are not published.", "source_ids": ["schedule", "entry"]},
            {"key": "location", "label": "Location", "value": "Remote participation across the United States.", "source_ids": ["schedule"]},
            {"key": "cost", "label": "Published cost", "value": "Combine registration: free. Required Adult Athlete ID: $39.50.", "source_ids": ["schedule"]},
            {"key": "eligibility", "label": "Requirements", "value": "Age 18+ by December 31, 2027 and a valid Athlete ID. Confirm the applicable cycle and your eligibility with USA Football.", "source_ids": ["schedule"]},
            {"key": "contact", "label": "Contact", "value": None, "source_ids": []},
        ],
        "action": {"kind": "open_source", "label": "View official details", "href": DIGITAL,
                   "recipient": None, "purpose": None, "source_ids": ["schedule"]},
        "sources": [
            {"id": "schedule", "title": "USA Football digital combines — schedule and requirements", "url": DIGITAL, "checked_at": CHECKED, "expires_at": EXPIRES},
            {"id": "entry", "title": "Official adult combine link on GMTM", "url": GMTM_COMBINE, "checked_at": COMBINE_ENTRY_CHECKED, "expires_at": COMBINE_ENTRY_EXPIRES},
        ],
    },
    {
        "id": "usaf-high-performance-inquiry", "title": "Ask about your next evaluation",
        "organization": "USA Football High Performance", "kind": "contact", "format": "remote",
        "categories": ["men", "women"], "status": "published_route",
        "focuses": ["national_team"], "state": None, "participation": "information",
        "summary": "Prepare a focused question for the publicly listed High Performance department about upcoming adult evaluations and requirements.",
        "valid_until": EXPIRES, "opens_at": None, "closes_at": None,
        "facts": [
            {"key": "dates", "label": "Dates", "value": None, "source_ids": []},
            {"key": "location", "label": "Location", "value": None, "source_ids": []},
            {"key": "cost", "label": "Cost", "value": None, "source_ids": []},
            {"key": "eligibility", "label": "Requirements", "value": None, "source_ids": []},
            {"key": "contact", "label": "Public program contact", "value": "teamusa@usafootball.com — High Performance department. No named recipient or response time is published.", "source_ids": ["contact"]},
        ],
        "action": {"kind": "prepare_introduction", "label": "Prepare introduction", "href": CONTACT,
                   "recipient": "USA Football High Performance",
                   "purpose": "Could you clarify the next adult flag evaluation dates, any in-person opportunities, and the requirements for the applicable national-team cycle?",
                   "source_ids": ["contact"]},
        "sources": [{"id": "contact", "title": "USA Football national team — High Performance contact", "url": CONTACT, "checked_at": CHECKED, "expires_at": EXPIRES}],
    },
)

# Competition research: docs/research/adult-flag-events-2026-09-23.md.
# Calendar cutoffs below are conservative internal withdrawals, not official UTC deadlines.
RECORDS += ({'id': 'iflag-battle-orlando-2026',
  'title': 'Battle Orlando · October 2026',
  'organization': 'International Flag League',
  'kind': 'event',
  'format': 'in_person',
  'categories': ['men', 'women'],
  'focuses': ['competition'],
  'state': 'FL',
  'participation': 'team',
  'status': 'check_details',
  'summary': 'Compete with a team in published adult divisions. Confirm roster rules, availability and full costs before '
             'planning travel.',
  'valid_until': ORLANDO_EXPIRES,
  'opens_at': None,
  'closes_at': '2026-10-02T00:00:00Z',
  'facts': [{'key': 'dates',
             'label': 'Event and registration dates',
             'value': 'Oct 10–11, 2026. Registration ends Oct 2 at 7pm; organizer says EST. Confirm the timezone.',
             'source_ids': ['event']},
            {'key': 'location',
             'label': 'Venue',
             'value': 'Simmers Young Park, Winter Haven, Florida (marketed as Orlando).',
             'source_ids': ['event']},
            {'key': 'cost',
             'label': 'Team entry cost',
             'value': '$375 per team/division; referees included. $50 deposit, balance due Sep 25 at 7pm EST. Teams supply '
                      'flags; final checkout and travel costs unverified.',
             'source_ids': ['event']},
            {'key': 'eligibility',
             'label': 'Entry requirements',
             'value': "Open-invite team entry; no prior qualification required. Adult men's, women's and coed divisions. "
                      'Confirm age, ranking and roster rules. Individual placement is not established.',
             'source_ids': ['event']},
            {'key': 'contact',
             'label': 'Organizer contact',
             'value': 'contact@iflag.org — general organizer inquiries.',
             'source_ids': ['contact']}],
  'action': {'kind': 'open_source',
             'label': 'Review team entry',
             'href': 'https://iflag.org/tournaments/2026-battle-orlando/',
             'recipient': None,
             'purpose': None,
             'source_ids': ['event']},
  'sources': [{'id': 'event',
               'title': 'Official event details and team divisions',
               'url': 'https://iflag.org/tournaments/2026-battle-orlando/',
               'checked_at': CHECKED,
               'expires_at': ORLANDO_EXPIRES},
              {'id': 'contact',
               'title': 'International Flag League — contact',
               'url': 'https://iflag.org/contact/',
               'checked_at': CHECKED,
               'expires_at': ORLANDO_EXPIRES}]},
 {'id': 'iflag-tampa-nationals-2027',
  'title': 'Tampa National Championships · 2027',
  'organization': 'International Flag League',
  'kind': 'event',
  'format': 'in_person',
  'categories': ['men', 'women'],
  'focuses': ['competition'],
  'state': 'FL',
  'participation': 'team',
  'status': 'check_details',
  'summary': 'Compete with a team in published adult divisions. Confirm roster rules, availability and full costs before '
             'planning travel.',
  'valid_until': EXPIRES,
  'opens_at': None,
  'closes_at': '2026-12-04T00:00:00Z',
  'facts': [{'key': 'dates',
             'label': 'Event and registration dates',
             'value': 'Jan 14–17, 2027. New registration ends Dec 4, 2026; cutoff time and timezone not specified.',
             'source_ids': ['event']},
            {'key': 'location',
             'label': 'Venue',
             'value': 'Tournament Sportsplex of Tampa Bay, Tampa, Florida.',
             'source_ids': ['event']},
            {'key': 'cost',
             'label': 'Team entry cost',
             'value': '5v5 non-contact: $375–$450 per team/division; referees included. $50 deposit; balance due Oct 9, 2026 '
                      'at 7pm EST, possibly earlier if full. $50 late fee from Nov 27 at 7pm EST for 5v5. Confirm timezone. '
                      'Parking TBD; teams bring flags. Checkout and travel totals unverified.',
             'source_ids': ['event']},
            {'key': 'eligibility',
             'label': 'Entry requirements',
             'value': "Open-invite team entry; no prior qualification required. Adult men's, women's and coed divisions. "
                      'Confirm age, ranking and roster rules. Individual placement is not established.',
             'source_ids': ['event']},
            {'key': 'contact',
             'label': 'Organizer contact',
             'value': 'contact@iflag.org — general organizer inquiries.',
             'source_ids': ['contact']}],
  'action': {'kind': 'open_source',
             'label': 'Review team entry',
             'href': 'https://iflag.org/tournaments/2027-tampa-national-championships/',
             'recipient': None,
             'purpose': None,
             'source_ids': ['event']},
  'sources': [{'id': 'event',
               'title': 'Official event details and team divisions',
               'url': 'https://iflag.org/tournaments/2027-tampa-national-championships/',
               'checked_at': CHECKED,
               'expires_at': EXPIRES},
              {'id': 'contact',
               'title': 'International Flag League — contact',
               'url': 'https://iflag.org/contact/',
               'checked_at': CHECKED,
               'expires_at': EXPIRES}]},
 {'id': 'iflag-team-access-inquiry',
  'title': 'Find your way into competition',
  'organization': 'International Flag League',
  'kind': 'contact',
  'format': 'remote',
  'categories': ['men', 'women'],
  'focuses': ['competition'],
  'state': None,
  'participation': 'information',
  'status': 'published_route',
  'summary': 'Ask the organizer about team access, possible free-agent routes and division requirements. A place on a team '
             'is not confirmed.',
  'valid_until': EXPIRES,
  'opens_at': None,
  'closes_at': None,
  'facts': [{'key': 'dates', 'label': 'Dates', 'value': None, 'source_ids': []},
            {'key': 'location', 'label': 'Location', 'value': None, 'source_ids': []},
            {'key': 'cost', 'label': 'Cost', 'value': None, 'source_ids': []},
            {'key': 'eligibility', 'label': 'Requirements', 'value': None, 'source_ids': []},
            {'key': 'contact',
             'label': 'Public organizer contact',
             'value': 'contact@iflag.org — general inquiries. Team placement and response time are not confirmed.',
             'source_ids': ['contact']}],
  'action': {'kind': 'prepare_introduction',
             'label': 'Ask about team access',
             'href': 'https://iflag.org/contact/',
             'recipient': 'International Flag League team',
             'purpose': 'Do you offer a way to join an existing adult team or enter as a free agent? How can I confirm the '
                        'appropriate division, eligibility requirements and total mandatory costs?',
             'source_ids': ['contact']},
  'sources': [{'id': 'contact',
               'title': 'International Flag League — contact',
               'url': 'https://iflag.org/contact/',
               'checked_at': CHECKED,
               'expires_at': EXPIRES}]})
